spring:
  application:
    name: PickleBallVCB
  security:
    user:
      name: admin
      password: 123456

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:E:/_app/PickleBallVCB/run/database/database;AUTO_SERVER=TRUE
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: oracle
    #    database-platform: org.hibernate.dialect.Oracle12cDialect
    database-platform: org.hibernate.dialect.H2Dialect
    #database-platform: org.hibernate.dialect.OracleDialect
    open-in-view: false
  mvc:
    dispatch-trace-request: true
  h2:
    console:
      enabled: true
      path=: /h2-console
  thymeleaf:
    cache: false

scheduler:

logging:
  level:
    org:
      springframework: WARN
      hibernate: WARN
    root: WARN

# setting port khi run app
server:
  port: 8088

springdoc:
  packagesToScan: com.vcb
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

